version: "3"
services:
  grafana:
    container_name: grafana
    image: docker.ready4.fun/grafana/grafana
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana

  prometheus:
    container_name: prometheus
    image: docker.ready4.fun/prom/prometheus
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/proemtheus/consoles'
      - '--web.enable-admin-api'

  cadvisor:
    container_name: cadvisor
    image: gcr.ready4.fun/cadvisor/cadvisor:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"
    command:
      - '-port=9250'


  node-exporter:
    container_name: node-exporter
    image: docker.ready4.fun/prom/node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  smartctl:
    container_name: smartctl
    image: docker.ready4.fun/matusnovak/prometheus-smartctl
    restart: unless-stopped
    privileged: true
    network_mode: host

volumes:
  grafana:
  prometheus:
